environments:
    - name: dev
      configs:
          endpoints:
              production:
                  url: 'https://dev.wso2.com'
              sandbox:
                  url: 'https://dev.sandbox.wso2.com'
          security:
              enabled:
              type:
              username:
              password:
          deploymentEnvironments:
              - displayOnDevportal:
                deploymentEnvironment:
                deploymentVhost:
              - displayOnDevportal:
                deploymentEnvironment:  
                deploymentVhost:
          certs:
              - hostName:
                alias:
                path:
              - hostName:
                alias:
                path:
          mutualSslCerts:
              - tierName:
                alias:
                path:
              - tierName:
                alias:
                path:
          policies:
              - 
              -  
    - name: prod
      configs:
          endpoints:
              production:
                  url: 'https://prod.wso2.com'
              sandbox:
                  url: 'https://prod.sandbox.wso2.com'

